validation:
  columns: 34
  dense: 195
prepare:
  epochs: 74
  trees: 74
  batch_size: 335
  layers: 2
  learning_rate: 0.12328
concurrent:
  columns: 79
  sample: 1.13872
  batch_size: 136
  layers: 4
  min_split: 32
tagging:
  drop: 0.31194
  features: 2952
  batch_size: 118
  tags: 116
  columns: 17
model:
  drop: 0.22109
  min_features: 101
  max_features: 2686
