validation:
  columns: 35
  dense: 153
prepare:
  epochs: 69
  trees: 78
  batch_size: 402
  layers: 2
  learning_rate: 0.09913
concurrent:
  columns: 70
  sample: 1.0979
  batch_size: 136
  layers: 4
  min_split: 24
tagging:
  drop: 0.26048
  features: 4392
  batch_size: 145
  tags: 116
  columns: 15
model:
  drop: 0.22906
  min_features: 103
  max_features: 2656
