validation:
  columns: 34
  dense: 166
prepare:
  epochs: 98
  trees: 73
  batch_size: 454
  layers: 2
  learning_rate: 0.14752
concurrent:
  columns: 74
  sample: 1.02132
  batch_size: 121
  layers: 5
  min_split: 31
tagging:
  drop: 0.25343
  features: 3150
  batch_size: 135
  tags: 109
  columns: 15
model:
  drop: 0.2
  min_features: 105
  max_features: 2211
