validation:
  columns: 30
  dense: 200
prepare:
  epochs: 72
  trees: 74
  batch_size: 459
  layers: 2
  learning_rate: 0.09555
concurrent:
  columns: 53
  sample: 1.0
  batch_size: 112
  layers: 6
  min_split: 27
tagging:
  drop: 0.36795
  features: 3782
  batch_size: 144
  tags: 130
  columns: 15
model:
  drop: 0.2
  min_features: 75
  max_features: 2606
