validation:
  columns: 30
  dense: 200
prepare:
  epochs: 61
  trees: 52
  batch_size: 358
  layers: 1
  learning_rate: 0.12244
concurrent:
  columns: 53
  sample: 1.0
  batch_size: 112
  layers: 6
  min_split: 27
tagging:
  drop: 0.36795
  features: 3782
  batch_size: 144
  tags: 130
  columns: 15
model:
  drop: 0.2
  min_features: 100
  max_features: 2606
