validation:
  columns: 31
  dense: 246
prepare:
  epochs: 70
  trees: 63
  batch_size: 403
  layers: 2
  learning_rate: 0.14155
concurrent:
  columns: 68
  sample: 0.98481
  batch_size: 86
  layers: 6
  min_split: 27
tagging:
  drop: 0.24599
  features: 3833
  batch_size: 119
  tags: 156
  columns: 17
model:
  drop: 0.18837
  min_features: 121
  max_features: 2391
