validation:
  columns: 36
  dense: 195
prepare:
  epochs: 85
  trees: 55
  batch_size: 367
  layers: 2
  learning_rate: 0.12255
concurrent:
  columns: 79
  sample: 1.13872
  batch_size: 136
  layers: 4
  min_split: 36
tagging:
  drop: 0.31194
  features: 4255
  batch_size: 118
  tags: 116
  columns: 15
model:
  drop: 0.22577
  min_features: 101
  max_features: 2234
