validation:
  columns: 30
  dense: 200
prepare:
  epochs: 61
  trees: 52
  batch_size: 358
  layers: 1
  learning_rate: 0.12244
concurrent:
  columns: 75
  sample: 1.0
  batch_size: 112
  layers: 6
  min_split: 32
tagging:
  drop: 0.27869
  features: 3765
  batch_size: 144
  tags: 143
  columns: 15
model:
  drop: 0.2
  min_features: 100
  max_features: 2606
