validation:
  columns: 32
  dense: 198
prepare:
  epochs: 61
  trees: 61
  batch_size: 361
  layers: 2
  learning_rate: 0.10183
concurrent:
  columns: 68
  sample: 1.10455
  batch_size: 104
  layers: 5
  min_split: 32
tagging:
  drop: 0.33729
  features: 3102
  batch_size: 132
  tags: 105
  columns: 15
model:
  drop: 0.19968
  min_features: 91
  max_features: 2391
