validation:
  columns: 23
  dense: 221
prepare:
  epochs: 64
  trees: 53
  batch_size: 439
  layers: 1
  learning_rate: 0.1311
concurrent:
  columns: 68
  sample: 1.08424
  batch_size: 95
  layers: 6
  min_split: 28
tagging:
  drop: 0.25906
  features: 3986
  batch_size: 127
  tags: 156
  columns: 12
model:
  drop: 0.23765
  min_features: 110
  max_features: 2209
