validation:
  columns: 35
  dense: 196
prepare:
  epochs: 87
  trees: 59
  batch_size: 411
  layers: 2
  learning_rate: 0.14029
concurrent:
  columns: 68
  sample: 0.79179
  batch_size: 136
  layers: 7
  min_split: 31
tagging:
  drop: 0.26048
  features: 3671
  batch_size: 164
  tags: 143
  columns: 17
model:
  drop: 0.22906
  min_features: 103
  max_features: 1759
