validation:
  columns: 23
  dense: 231
prepare:
  epochs: 64
  trees: 55
  batch_size: 317
  layers: 2
  learning_rate: 0.1311
concurrent:
  columns: 68
  sample: 1.08424
  batch_size: 95
  layers: 6
  min_split: 27
tagging:
  drop: 0.25906
  features: 3986
  batch_size: 125
  tags: 156
  columns: 12
model:
  drop: 0.23765
  min_features: 104
  max_features: 2209
