validation:
  columns: 28
  dense: 196
prepare:
  epochs: 69
  trees: 63
  batch_size: 296
  layers: 2
  learning_rate: 0.09913
concurrent:
  columns: 57
  sample: 1.02849
  batch_size: 136
  layers: 4
  min_split: 28
tagging:
  drop: 0.26048
  features: 3825
  batch_size: 125
  tags: 116
  columns: 16
model:
  drop: 0.22906
  min_features: 103
  max_features: 1759
