validation:
  columns: 31
  dense: 246
prepare:
  epochs: 70
  trees: 63
  batch_size: 403
  layers: 2
  learning_rate: 0.14155
concurrent:
  columns: 68
  sample: 1.05057
  batch_size: 84
  layers: 5
  min_split: 27
tagging:
  drop: 0.24599
  features: 3833
  batch_size: 122
  tags: 151
  columns: 17
model:
  drop: 0.18837
  min_features: 121
  max_features: 2391
