validation:
  columns: 34
  dense: 158
prepare:
  epochs: 81
  trees: 55
  batch_size: 379
  layers: 2
  learning_rate: 0.13526
concurrent:
  columns: 62
  sample: 1.02248
  batch_size: 112
  layers: 6
  min_split: 30
tagging:
  drop: 0.36884
  features: 3782
  batch_size: 172
  tags: 100
  columns: 15
model:
  drop: 0.2
  min_features: 75
  max_features: 2606
