validation:
  columns: 23
  dense: 246
prepare:
  epochs: 85
  trees: 64
  batch_size: 360
  layers: 2
  learning_rate: 0.09943
concurrent:
  columns: 68
  sample: 1.10455
  batch_size: 90
  layers: 5
  min_split: 32
tagging:
  drop: 0.32059
  features: 3833
  batch_size: 132
  tags: 154
  columns: 14
model:
  drop: 0.15825
  min_features: 91
  max_features: 2391
