validation:
  columns: 34
  dense: 195
prepare:
  epochs: 61
  trees: 69
  batch_size: 323
  layers: 2
  learning_rate: 0.09147
concurrent:
  columns: 79
  sample: 0.86317
  batch_size: 95
  layers: 4
  min_split: 28
tagging:
  drop: 0.32663
  features: 3364
  batch_size: 113
  tags: 143
  columns: 17
model:
  drop: 0.17888
  min_features: 114
  max_features: 2239
