validation:
  columns: 34
  dense: 195
prepare:
  epochs: 80
  trees: 74
  batch_size: 417
  layers: 2
  learning_rate: 0.12174
concurrent:
  columns: 79
  sample: 1.13872
  batch_size: 136
  layers: 4
  min_split: 28
tagging:
  drop: 0.32663
  features: 3364
  batch_size: 113
  tags: 143
  columns: 13
model:
  drop: 0.17888
  min_features: 114
  max_features: 2686
