validation:
  columns: 35
  dense: 196
prepare:
  epochs: 96
  trees: 74
  batch_size: 399
  layers: 2
  learning_rate: 0.1349
concurrent:
  columns: 68
  sample: 1.02849
  batch_size: 136
  layers: 7
  min_split: 31
tagging:
  drop: 0.26048
  features: 3671
  batch_size: 164
  tags: 143
  columns: 17
model:
  drop: 0.22906
  min_features: 103
  max_features: 1759
