validation:
  columns: 35
  dense: 166
prepare:
  epochs: 98
  trees: 61
  batch_size: 348
  layers: 1
  learning_rate: 0.13919
concurrent:
  columns: 74
  sample: 1.02132
  batch_size: 121
  layers: 6
  min_split: 33
tagging:
  drop: 0.25343
  features: 3150
  batch_size: 135
  tags: 118
  columns: 12
model:
  drop: 0.18837
  min_features: 105
  max_features: 2211
