validation:
  columns: 23
  dense: 222
prepare:
  epochs: 62
  trees: 59
  batch_size: 444
  layers: 2
  learning_rate: 0.10249
concurrent:
  columns: 68
  sample: 1.08424
  batch_size: 104
  layers: 5
  min_split: 30
tagging:
  drop: 0.36089
  features: 3102
  batch_size: 132
  tags: 102
  columns: 14
model:
  drop: 0.23765
  min_features: 86
  max_features: 2590
