validation:
  columns: 23
  dense: 168
prepare:
  epochs: 61
  trees: 56
  batch_size: 323
  layers: 2
  learning_rate: 0.14589
concurrent:
  columns: 52
  sample: 0.86317
  batch_size: 95
  layers: 6
  min_split: 28
tagging:
  drop: 0.32663
  features: 3986
  batch_size: 127
  tags: 143
  columns: 12
model:
  drop: 0.17023
  min_features: 101
  max_features: 2239
