validation:
  columns: 28
  dense: 196
prepare:
  epochs: 96
  trees: 74
  batch_size: 399
  layers: 1
  learning_rate: 0.1349
concurrent:
  columns: 68
  sample: 1.02849
  batch_size: 136
  layers: 7
  min_split: 28
tagging:
  drop: 0.26048
  features: 3671
  batch_size: 125
  tags: 116
  columns: 16
model:
  drop: 0.22906
  min_features: 103
  max_features: 1759
