validation:
  columns: 23
  dense: 168
prepare:
  epochs: 99
  trees: 80
  batch_size: 382
  layers: 2
  learning_rate: 0.1222
concurrent:
  columns: 52
  sample: 0.93962
  batch_size: 95
  layers: 6
  min_split: 28
tagging:
  drop: 0.25906
  features: 3986
  batch_size: 127
  tags: 143
  columns: 12
model:
  drop: 0.17023
  min_features: 101
  max_features: 2209
