validation:
  columns: 25
  dense: 166
prepare:
  epochs: 95
  trees: 63
  batch_size: 403
  layers: 1
  learning_rate: 0.14093
concurrent:
  columns: 74
  sample: 0.98481
  batch_size: 86
  layers: 6
  min_split: 33
tagging:
  drop: 0.24599
  features: 3479
  batch_size: 155
  tags: 130
  columns: 17
model:
  drop: 0.18837
  min_features: 121
  max_features: 2391
