validation:
  columns: 36
  dense: 225
prepare:
  epochs: 69
  trees: 78
  batch_size: 402
  layers: 2
  learning_rate: 0.09166
concurrent:
  columns: 63
  sample: 0.9988
  batch_size: 136
  layers: 4
  min_split: 36
tagging:
  drop: 0.31194
  features: 4392
  batch_size: 118
  tags: 116
  columns: 15
model:
  drop: 0.22577
  min_features: 101
  max_features: 2809
