validation:
  columns: 23
  dense: 153
prepare:
  epochs: 69
  trees: 78
  batch_size: 402
  layers: 2
  learning_rate: 0.12076
concurrent:
  columns: 54
  sample: 0.9988
  batch_size: 136
  layers: 4
  min_split: 36
tagging:
  drop: 0.31194
  features: 4392
  batch_size: 145
  tags: 116
  columns: 16
model:
  drop: 0.22577
  min_features: 103
  max_features: 2809
