validation:
  columns: 34
  dense: 158
prepare:
  epochs: 98
  trees: 73
  batch_size: 454
  layers: 2
  learning_rate: 0.10546
concurrent:
  columns: 62
  sample: 1.02248
  batch_size: 119
  layers: 6
  min_split: 30
tagging:
  drop: 0.30167
  features: 3782
  batch_size: 172
  tags: 109
  columns: 15
model:
  drop: 0.2
  min_features: 96
  max_features: 2606
