validation:
  columns: 22
  dense: 166
prepare:
  epochs: 90
  trees: 62
  batch_size: 325
  layers: 1
  learning_rate: 0.13919
concurrent:
  columns: 74
  sample: 1.02132
  batch_size: 121
  layers: 6
  min_split: 33
tagging:
  drop: 0.25343
  features: 3395
  batch_size: 135
  tags: 130
  columns: 12
model:
  drop: 0.18837
  min_features: 121
  max_features: 2211
