stages:
  split:
    cmd: python split.py phrases.csv phrases-train.csv phrases-test.csv
    deps:
    - phrases.csv
    - split.py
    outs:
    - phrases-test.csv
    - phrases-train.csv
  featurize:
    cmd: python featurize.py phrases-train.csv phrases-train-feats.csv
    deps:
    - featurize.py
    - phrases-train.csv
    params:
    - featurize.min_split
    - featurize.random_state
    - featurize.sample
    - featurize.split
    - featurize.tags
    - featurize.trees
    outs:
    - phrases-train-feats.csv
  train:
    cmd: python train.py phrases-train-feats.csv model.json
    deps:
    - phrases-train-feats.csv
    - train.py
    params:
    - concurrent.dense
    - concurrent.estimators
    - concurrent.seed
    - concurrent.trees
    - model.dense
    - model.max_features
    - model.num_est
    - model.random_state
    - preprocessing.dense
    - preprocessing.epochs
    - preprocessing.folds
    - preprocessing.max_depth
    - preprocessing.max_features
    - preprocessing.random_state
    - preprocessing.split
    - variables.min_features
    - variables.min_split
    - variables.tags
    - variables.trees
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json phrases-test.csv
    deps:
    - evaluate.py
    - model.json
    - phrases-test.csv
    metrics:
    - metrics.json:
        cache: false
