model:
  num_est: 91
  random_state: 707918943
  max_features: 639
  dense: 346
featurize:
  sample: 0.68453
  min_split: 15
  tags: 101
  random_state: 21358746
  trees: 14
  split: 0.16161
preprocessing:
  max_features: 3905
  random_state: 286295522
  epochs: 60
  max_depth: 29
  folds: 14
  dense: 452
  split: 0.58761
variables:
  trees: 63
  tags: 24
  min_features: 1755
  min_split: 64
concurrent:
  estimators: 145
  seed: 1075719985
  trees: 54
  dense: 514
