model:
  num_est: 115
  random_state: 970667962
  max_features: 541
  dense: 346
featurize:
  sample: 0.68453
  min_split: 15
  tags: 101
  random_state: 21358746
  trees: 14
  split: 0.16161
preprocessing:
  max_features: 4214
  random_state: 286295522
  epochs: 68
  max_depth: 20
  folds: 14
  dense: 452
  split: 0.58761
variables:
  trees: 63
  tags: 21
  min_features: 1755
  min_split: 53
concurrent:
  estimators: 151
  seed: 702970938
  trees: 54
  dense: 604
