model:
  num_est: 91
  random_state: 707918943
  max_features: 639
  dense: 346
featurize:
  sample: 0.9312
  min_split: 18
  tags: 103
  random_state: 18260475
  trees: 17
  split: 0.20728
preprocessing:
  max_features: 3905
  random_state: 286295522
  epochs: 60
  max_depth: 29
  folds: 14
  dense: 452
  split: 0.58761
variables:
  trees: 63
  tags: 24
  min_features: 1384
  min_split: 54
concurrent:
  estimators: 145
  seed: 805068757
  trees: 54
  dense: 514
