model:
  num_est: 91
  random_state: 707918943
  max_features: 442
  dense: 346
featurize:
  sample: 0.83799
  min_split: 13
  tags: 107
  random_state: 21585975
  trees: 13
  split: 0.21908
preprocessing:
  max_features: 3905
  random_state: 286295522
  epochs: 60
  max_depth: 29
  folds: 13
  dense: 452
  split: 0.58761
variables:
  trees: 98
  tags: 24
  min_features: 1384
  min_split: 74
concurrent:
  estimators: 152
  seed: 895714802
  trees: 54
  dense: 514
