model:
  num_est: 88
  random_state: 771416303
  max_features: 600
  dense: 392
featurize:
  sample: 0.91903
  min_split: 17
  tags: 110
  random_state: 17441692
  trees: 14
  split: 0.1706
preprocessing:
  max_features: 3296
  random_state: 286295522
  epochs: 58
  max_depth: 21
  folds: 13
  dense: 402
  split: 0.45484
variables:
  trees: 62
  tags: 24
  min_features: 1826
  min_split: 72
concurrent:
  estimators: 142
  seed: 966664176
  trees: 48
  dense: 402
