model:
  num_est: 115
  random_state: 723175047
  max_features: 635
  dense: 346
featurize:
  sample: 0.68453
  min_split: 13
  tags: 81
  random_state: 20017709
  trees: 16
  split: 0.21767
preprocessing:
  max_features: 4214
  random_state: 313811340
  epochs: 68
  max_depth: 20
  folds: 14
  dense: 436
  split: 0.41567
variables:
  trees: 83
  tags: 21
  min_features: 1755
  min_split: 53
concurrent:
  estimators: 144
  seed: 702970938
  trees: 54
  dense: 604
