model:
  num_est: 97
  random_state: 723175047
  max_features: 508
  dense: 431
featurize:
  sample: 0.84131
  min_split: 13
  tags: 81
  random_state: 20017709
  trees: 16
  split: 0.19149
preprocessing:
  max_features: 3595
  random_state: 306382453
  epochs: 68
  max_depth: 24
  folds: 14
  dense: 436
  split: 0.5281
variables:
  trees: 83
  tags: 21
  min_features: 1755
  min_split: 53
concurrent:
  estimators: 144
  seed: 702970938
  trees: 54
  dense: 392
