model:
  num_est: 91
  random_state: 771416303
  max_features: 442
  dense: 310
featurize:
  sample: 0.91903
  min_split: 17
  tags: 110
  random_state: 17441692
  trees: 11
  split: 0.1706
preprocessing:
  max_features: 3240
  random_state: 286295522
  epochs: 42
  max_depth: 21
  folds: 13
  dense: 402
  split: 0.5734
variables:
  trees: 86
  tags: 24
  min_features: 1826
  min_split: 74
concurrent:
  estimators: 142
  seed: 966664176
  trees: 43
  dense: 604
