model:
  num_est: 97
  random_state: 723175047
  max_features: 508
  dense: 431
featurize:
  sample: 0.78761
  min_split: 19
  tags: 116
  random_state: 22706159
  trees: 14
  split: 0.17286
preprocessing:
  max_features: 3595
  random_state: 306382453
  epochs: 68
  max_depth: 24
  folds: 14
  dense: 436
  split: 0.5281
variables:
  trees: 83
  tags: 21
  min_features: 1756
  min_split: 53
concurrent:
  estimators: 144
  seed: 702970938
  trees: 54
  dense: 392
