model:
  num_est: 113
  random_state: 723175047
  max_features: 547
  dense: 405
featurize:
  sample: 0.76964
  min_split: 17
  tags: 84
  random_state: 21409827
  trees: 14
  split: 0.18912
preprocessing:
  max_features: 4267
  random_state: 306382453
  epochs: 68
  max_depth: 25
  folds: 14
  dense: 436
  split: 0.5281
variables:
  trees: 81
  tags: 21
  min_features: 1250
  min_split: 53
concurrent:
  estimators: 144
  seed: 702970938
  trees: 54
  dense: 392
