model:
  num_est: 122
  random_state: 951010402
  max_features: 550
  dense: 405
featurize:
  sample: 0.75
  min_split: 13
  tags: 104
  random_state: 18292594
  trees: 15
  split: 0.24366
preprocessing:
  max_features: 4250
  random_state: 306382453
  epochs: 54
  max_depth: 25
  folds: 12
  dense: 436
  split: 0.5281
variables:
  trees: 81
  tags: 33
  min_features: 1650
  min_split: 53
concurrent:
  estimators: 144
  seed: 911123663
  trees: 54
  dense: 408
