model:
  num_est: 91
  random_state: 707918943
  max_features: 442
  dense: 346
featurize:
  sample: 0.83799
  min_split: 19
  tags: 81
  random_state: 21946169
  trees: 18
  split: 0.17178
preprocessing:
  max_features: 3905
  random_state: 286295522
  epochs: 60
  max_depth: 29
  folds: 13
  dense: 452
  split: 0.58761
variables:
  trees: 63
  tags: 24
  min_features: 1384
  min_split: 54
concurrent:
  estimators: 152
  seed: 805068757
  trees: 54
  dense: 514
