model:
  num_est: 88
  random_state: 842966265
  max_features: 600
  dense: 392
featurize:
  sample: 0.84714
  min_split: 14
  tags: 111
  random_state: 17112274
  trees: 14
  split: 0.18417
preprocessing:
  max_features: 4256
  random_state: 286295522
  epochs: 58
  max_depth: 19
  folds: 13
  dense: 428
  split: 0.45484
variables:
  trees: 62
  tags: 24
  min_features: 1826
  min_split: 72
concurrent:
  estimators: 128
  seed: 966664176
  trees: 48
  dense: 465
