model:
  num_est: 91
  random_state: 698713468
  max_features: 442
  dense: 346
featurize:
  sample: 0.69157
  min_split: 17
  tags: 107
  random_state: 22077546
  trees: 15
  split: 0.21908
preprocessing:
  max_features: 4750
  random_state: 286295522
  epochs: 42
  max_depth: 21
  folds: 13
  dense: 452
  split: 0.61124
variables:
  trees: 86
  tags: 24
  min_features: 2046
  min_split: 74
concurrent:
  estimators: 152
  seed: 895714802
  trees: 43
  dense: 604
