model:
  num_est: 91
  random_state: 771416303
  max_features: 442
  dense: 346
featurize:
  sample: 0.60621
  min_split: 12
  tags: 110
  random_state: 17441692
  trees: 17
  split: 0.2216
preprocessing:
  max_features: 3240
  random_state: 286295522
  epochs: 42
  max_depth: 21
  folds: 13
  dense: 402
  split: 0.5734
variables:
  trees: 86
  tags: 24
  min_features: 1971
  min_split: 74
concurrent:
  estimators: 137
  seed: 895714802
  trees: 43
  dense: 604
