concurrent:
  layers: 4
  dense: 739
  trees: 73
  features: 1857
  max_depth: 18
  threads: 15
  num_est: 121
variables:
  min_features: 1857
  features: 2257
  learning_rate: 0.07588
  batch_size: 674
  split: 0.39322
preprocessing:
  seed: 280306941
  trees: 88
  weight_factor: 0.21503
  passes: 1
  max_features: 289
  drop: 0.19105
  num_est: 110
  ngrams: 1
  split: 0.26817
settings:
  layers: 7
  batch_size: 721
  split: 0.075
  features: 1439
  min_split: 99
model:
  min_features: 3583
  batch_size: 1083
  seed: 50054803
