concurrent:
  layers: 6
  dense: 590
  trees: 79
  features: 1970
  max_depth: 24
  threads: 17
  num_est: 125
variables:
  min_features: 1998
  features: 1599
  learning_rate: 0.0876
  batch_size: 660
  split: 0.35653
preprocessing:
  seed: 269128075
  trees: 93
  weight_factor: 0.15099
  passes: 1
  max_features: 350
  drop: 0.1925
  num_est: 118
  ngrams: 1
  split: 0.3
settings:
  layers: 4
  batch_size: 663
  split: 0.08314
  features: 1327
  min_split: 93
model:
  min_features: 2430
  batch_size: 921
  seed: 43820241
