concurrent:
  layers: 5
  dense: 739
  trees: 73
  features: 1667
  max_depth: 20
  threads: 17
  num_est: 114
variables:
  min_features: 2563
  features: 2118
  learning_rate: 0.0876
  batch_size: 569
  split: 0.39526
preprocessing:
  seed: 280306941
  trees: 87
  weight_factor: 0.15099
  passes: 1
  max_features: 376
  drop: 0.19105
  num_est: 117
  ngrams: 1
  split: 0.26817
settings:
  layers: 5
  batch_size: 663
  split: 0.07572
  features: 1327
  min_split: 93
model:
  min_features: 2430
  batch_size: 1083
  seed: 54031165
