concurrent:
  layers: 5
  dense: 739
  trees: 61
  features: 1926
  max_depth: 20
  threads: 17
  num_est: 114
variables:
  min_features: 2563
  features: 2118
  learning_rate: 0.0876
  batch_size: 805
  split: 0.31392
preprocessing:
  seed: 280306941
  trees: 87
  weight_factor: 0.15099
  passes: 2
  max_features: 342
  drop: 0.19105
  num_est: 95
  ngrams: 1
  split: 0.24729
settings:
  layers: 5
  batch_size: 663
  split: 0.07572
  features: 1327
  min_split: 93
model:
  min_features: 2430
  batch_size: 1083
  seed: 47301599
