concurrent:
  layers: 6
  dense: 565
  trees: 61
  features: 1926
  max_depth: 16
  threads: 17
  num_est: 114
variables:
  min_features: 2563
  features: 1916
  learning_rate: 0.0876
  batch_size: 805
  split: 0.35653
preprocessing:
  seed: 280306941
  trees: 93
  weight_factor: 0.15099
  passes: 1
  max_features: 410
  drop: 0.19105
  num_est: 87
  ngrams: 1
  split: 0.24729
settings:
  layers: 5
  batch_size: 663
  split: 0.07572
  features: 1327
  min_split: 93
model:
  min_features: 2430
  batch_size: 921
  seed: 52293081
