concurrent:
  layers: 4
  dense: 739
  trees: 73
  features: 2427
  max_depth: 18
  threads: 17
  num_est: 132
variables:
  min_features: 2563
  features: 2257
  learning_rate: 0.09653
  batch_size: 517
  split: 0.39526
preprocessing:
  seed: 280306941
  trees: 88
  weight_factor: 0.23837
  passes: 1
  max_features: 376
  drop: 0.19105
  num_est: 90
  ngrams: 1
  split: 0.26817
settings:
  layers: 6
  batch_size: 663
  split: 0.07572
  features: 1439
  min_split: 65
model:
  min_features: 3427
  batch_size: 1083
  seed: 37733230
