concurrent:
  layers: 4
  dense: 574
  trees: 72
  features: 1684
  max_depth: 24
  threads: 17
  num_est: 130
variables:
  min_features: 1998
  features: 1735
  learning_rate: 0.08112
  batch_size: 531
  split: 0.35653
preprocessing:
  seed: 269128075
  trees: 64
  weight_factor: 0.15092
  passes: 1
  max_features: 350
  drop: 0.2
  num_est: 98
  ngrams: 2
  split: 0.3
settings:
  layers: 4
  batch_size: 800
  split: 0.08314
  features: 1550
  min_split: 88
model:
  min_features: 3352
  batch_size: 921
  seed: 43820241
