tagging:
  learning_rate: 0.09045
  tags: 118
  epochs: 18
  sample: 0.93601
  split: 0.10786
settings:
  layers: 1
  random_state: 794927742
  columns: 70
  epochs: 4
concurrent:
  columns: 11
  tags: 108
  split: 0.1075
  random_state: 206562972
  dense: 518
  estimators: 218
featurize:
  random_state: 479583692
  batch_size: 1225
  layers: 1
  weight_factor: 0.09853
model:
  trees: 11
  estimators: 133
  min_features: 3731
  num_est: 75
