tagging:
  learning_rate: 0.10718
  tags: 116
  epochs: 20
  sample: 0.80045
  split: 0.11513
settings:
  layers: 2
  random_state: 794927742
  columns: 69
  epochs: 4
concurrent:
  columns: 11
  tags: 123
  split: 0.09286
  random_state: 240371746
  dense: 412
  estimators: 179
featurize:
  random_state: 573254976
  batch_size: 1163
  layers: 1
  weight_factor: 0.08261
model:
  trees: 11
  estimators: 176
  min_features: 3349
  num_est: 121
