tagging:
  learning_rate: 0.09045
  tags: 118
  epochs: 22
  sample: 0.76943
  split: 0.10786
settings:
  layers: 2
  random_state: 794927742
  columns: 70
  epochs: 4
concurrent:
  columns: 11
  tags: 108
  split: 0.1075
  random_state: 206562972
  dense: 518
  estimators: 221
featurize:
  random_state: 397904786
  batch_size: 1191
  layers: 1
  weight_factor: 0.09853
model:
  trees: 11
  estimators: 176
  min_features: 3731
  num_est: 75
