tagging:
  learning_rate: 0.09729
  tags: 118
  epochs: 23
  sample: 1.18099
  split: 0.10786
settings:
  layers: 1
  random_state: 1158769847
  columns: 58
  epochs: 4
concurrent:
  columns: 9
  tags: 126
  split: 0.11842
  random_state: 248172105
  dense: 427
  estimators: 149
featurize:
  random_state: 450883920
  batch_size: 1061
  layers: 1
  weight_factor: 0.09327
model:
  trees: 11
  estimators: 189
  min_features: 2861
  num_est: 119
