tagging:
  learning_rate: 0.11781
  tags: 116
  epochs: 15
  sample: 0.87338
  split: 0.12172
settings:
  layers: 2
  random_state: 794927742
  columns: 70
  epochs: 5
concurrent:
  columns: 11
  tags: 100
  split: 0.09549
  random_state: 206562972
  dense: 518
  estimators: 221
featurize:
  random_state: 523136107
  batch_size: 1140
  layers: 1
  weight_factor: 0.12073
model:
  trees: 11
  estimators: 176
  min_features: 2873
  num_est: 75
