tagging:
  learning_rate: 0.09729
  tags: 118
  epochs: 18
  sample: 0.93601
  split: 0.10786
settings:
  layers: 1
  random_state: 1158769847
  columns: 55
  epochs: 4
concurrent:
  columns: 11
  tags: 108
  split: 0.11842
  random_state: 177755644
  dense: 427
  estimators: 218
featurize:
  random_state: 613526439
  batch_size: 1026
  layers: 1
  weight_factor: 0.08535
model:
  trees: 11
  estimators: 189
  min_features: 3731
  num_est: 119
