tagging:
  learning_rate: 0.11539
  tags: 116
  epochs: 19
  sample: 0.80045
  split: 0.12489
settings:
  layers: 2
  random_state: 794927742
  columns: 70
  epochs: 4
concurrent:
  columns: 13
  tags: 100
  split: 0.09286
  random_state: 195233372
  dense: 424
  estimators: 221
featurize:
  random_state: 484265930
  batch_size: 1057
  layers: 1
  weight_factor: 0.10791
model:
  trees: 11
  estimators: 176
  min_features: 4272
  num_est: 116
