tagging:
  learning_rate: 0.09729
  tags: 118
  epochs: 18
  sample: 0.9884
  split: 0.10786
settings:
  layers: 1
  random_state: 1158769847
  columns: 58
  epochs: 4
concurrent:
  columns: 11
  tags: 79
  split: 0.11842
  random_state: 179085327
  dense: 427
  estimators: 218
featurize:
  random_state: 640568746
  batch_size: 887
  layers: 2
  weight_factor: 0.08535
model:
  trees: 11
  estimators: 189
  min_features: 3731
  num_est: 119
