tagging:
  learning_rate: 0.10672
  tags: 118
  epochs: 23
  sample: 1.1798
  split: 0.08716
settings:
  layers: 1
  random_state: 1209647101
  columns: 58
  epochs: 4
concurrent:
  columns: 9
  tags: 126
  split: 0.11842
  random_state: 248172105
  dense: 427
  estimators: 149
featurize:
  random_state: 450883920
  batch_size: 1061
  layers: 2
  weight_factor: 0.09327
model:
  trees: 11
  estimators: 189
  min_features: 4256
  num_est: 119
