tagging:
  learning_rate: 0.08193
  tags: 119
  epochs: 20
  sample: 1.0
  split: 0.1
settings:
  layers: 1
  random_state: 1136267455
  columns: 60
  epochs: 4
concurrent:
  columns: 12
  tags: 96
  split: 0.1
  random_state: 210259065
  dense: 512
  estimators: 182
featurize:
  random_state: 624238774
  batch_size: 1160
  layers: 2
  weight_factor: 0.10341
model:
  trees: 9
  estimators: 186
  min_features: 3854
  num_est: 100
