tagging:
  learning_rate: 0.10672
  tags: 115
  epochs: 23
  sample: 1.1798
  split: 0.09644
settings:
  layers: 2
  random_state: 1209647101
  columns: 58
  epochs: 4
concurrent:
  columns: 9
  tags: 126
  split: 0.10915
  random_state: 248172105
  dense: 427
  estimators: 149
featurize:
  random_state: 487487213
  batch_size: 915
  layers: 2
  weight_factor: 0.11112
model:
  trees: 11
  estimators: 189
  min_features: 4256
  num_est: 119
