tagging:
  learning_rate: 0.1024
  tags: 119
  epochs: 20
  sample: 1.0
  split: 0.1
settings:
  layers: 2
  random_state: 1122335510
  columns: 60
  epochs: 4
concurrent:
  columns: 12
  tags: 81
  split: 0.1
  random_state: 177697809
  dense: 500
  estimators: 182
featurize:
  random_state: 551578135
  batch_size: 1043
  layers: 1
  weight_factor: 0.11556
model:
  trees: 9
  estimators: 133
  min_features: 3650
  num_est: 100
