tagging:
  learning_rate: 0.11781
  tags: 116
  epochs: 24
  sample: 0.80045
  split: 0.12172
settings:
  layers: 2
  random_state: 794927742
  columns: 70
  epochs: 4
concurrent:
  columns: 11
  tags: 100
  split: 0.09549
  random_state: 195233372
  dense: 424
  estimators: 221
featurize:
  random_state: 484265930
  batch_size: 1057
  layers: 1
  weight_factor: 0.10791
model:
  trees: 11
  estimators: 176
  min_features: 2873
  num_est: 75
