tagging:
  learning_rate: 0.08193
  tags: 119
  epochs: 23
  sample: 1.0
  split: 0.11027
settings:
  layers: 1
  random_state: 1070445768
  columns: 60
  epochs: 4
concurrent:
  columns: 9
  tags: 111
  split: 0.0974
  random_state: 248172105
  dense: 512
  estimators: 149
featurize:
  random_state: 511002373
  batch_size: 1144
  layers: 1
  weight_factor: 0.12094
model:
  trees: 14
  estimators: 189
  min_features: 3854
  num_est: 119
