tagging:
  learning_rate: 0.10672
  tags: 119
  epochs: 23
  sample: 1.1798
  split: 0.11879
settings:
  layers: 2
  random_state: 1021531880
  columns: 60
  epochs: 4
concurrent:
  columns: 9
  tags: 126
  split: 0.0974
  random_state: 248172105
  dense: 427
  estimators: 149
featurize:
  random_state: 511002373
  batch_size: 964
  layers: 1
  weight_factor: 0.07622
model:
  trees: 13
  estimators: 189
  min_features: 4256
  num_est: 119
