concurrent:
  ngrams: 7
  split: 0.23018
  min_features: 1476
  drop: 0.07713
  tags: 39
validation:
  batch_size: 663
  split: 0.27151
variables:
  random_state: 815902020
  threads: 5
tagging:
  threads: 28
  min_features: 830
  min_split: 44
  epochs: 30
preprocessing:
  min_features: 121
  layers: 4
  min_split: 73
  num_est: 87
  max_features: 830
