concurrent:
  ngrams: 6
  split: 0.19346
  min_features: 1450
  drop: 0.09869
  tags: 36
validation:
  batch_size: 680
  split: 0.33515
variables:
  random_state: 771011060
  threads: 5
tagging:
  threads: 24
  min_features: 846
  min_split: 37
  epochs: 33
preprocessing:
  min_features: 119
  layers: 4
  min_split: 65
  num_est: 78
  max_features: 649
