concurrent:
  ngrams: 6
  split: 0.21945
  min_features: 1476
  drop: 0.0825
  tags: 39
validation:
  batch_size: 663
  split: 0.32746
variables:
  random_state: 760009935
  threads: 6
tagging:
  threads: 28
  min_features: 687
  min_split: 40
  epochs: 40
preprocessing:
  min_features: 121
  layers: 4
  min_split: 55
  num_est: 87
  max_features: 562
