concurrent:
  ngrams: 6
  split: 0.21945
  min_features: 1519
  drop: 0.0825
  tags: 39
validation:
  batch_size: 663
  split: 0.32078
variables:
  random_state: 846343900
  threads: 6
tagging:
  threads: 36
  min_features: 842
  min_split: 40
  epochs: 40
preprocessing:
  min_features: 85
  layers: 3
  min_split: 71
  num_est: 63
  max_features: 643
