concurrent:
  ngrams: 6
  split: 0.2
  min_features: 1450
  drop: 0.1
  tags: 49
validation:
  batch_size: 640
  split: 0.3
variables:
  random_state: 698000000
  threads: 6
tagging:
  threads: 31
  min_features: 800
  min_split: 48
  epochs: 35
preprocessing:
  min_features: 100
  layers: 4
  min_split: 64
  num_est: 75
  max_features: 700
