concurrent:
  ngrams: 7
  split: 0.19741
  min_features: 1450
  drop: 0.09869
  tags: 42
validation:
  batch_size: 680
  split: 0.33515
variables:
  random_state: 652055155
  threads: 5
tagging:
  threads: 37
  min_features: 942
  min_split: 56
  epochs: 33
preprocessing:
  min_features: 119
  layers: 4
  min_split: 65
  num_est: 66
  max_features: 580
