concurrent:
  ngrams: 6
  split: 0.2
  min_features: 1450
  drop: 0.1
  tags: 49
validation:
  batch_size: 556
  split: 0.28618
variables:
  random_state: 610142014
  threads: 6
tagging:
  threads: 27
  min_features: 800
  min_split: 43
  epochs: 37
preprocessing:
  min_features: 92
  layers: 4
  min_split: 64
  num_est: 75
  max_features: 580
