concurrent:
  ngrams: 7
  split: 0.23018
  min_features: 1450
  drop: 0.09869
  tags: 40
validation:
  batch_size: 692
  split: 0.3072
variables:
  random_state: 771011060
  threads: 5
tagging:
  threads: 28
  min_features: 846
  min_split: 59
  epochs: 38
preprocessing:
  min_features: 119
  layers: 4
  min_split: 65
  num_est: 78
  max_features: 768
