concurrent:
  ngrams: 4
  split: 0.19741
  min_features: 1450
  drop: 0.09869
  tags: 42
validation:
  batch_size: 556
  split: 0.33515
variables:
  random_state: 610142014
  threads: 6
tagging:
  threads: 37
  min_features: 800
  min_split: 56
  epochs: 33
preprocessing:
  min_features: 119
  layers: 3
  min_split: 64
  num_est: 75
  max_features: 580
