concurrent:
  ngrams: 5
  split: 0.23018
  min_features: 1476
  drop: 0.07713
  tags: 51
validation:
  batch_size: 663
  split: 0.30992
variables:
  random_state: 815902020
  threads: 6
tagging:
  threads: 37
  min_features: 830
  min_split: 59
  epochs: 39
preprocessing:
  min_features: 121
  layers: 4
  min_split: 73
  num_est: 87
  max_features: 830
