tagging:
  trees: 57
  epochs: 28
  folds: 12
  estimators: 156
  seed: 500277000
concurrent:
  weight_factor: 0.19721
  ngrams: 4
  passes: 2
  features: 3089
  estimators: 160
train:
  estimators: 54
  batch_size: 796
  weight_factor: 0.2
  epochs: 42
settings:
  split: 0.08574
  estimators: 64
model:
  split: 0.59362
