tagging:
  trees: 67
  epochs: 29
  folds: 14
  estimators: 178
  seed: 451228327
concurrent:
  weight_factor: 0.18715
  ngrams: 4
  passes: 1
  features: 2684
  estimators: 130
train:
  estimators: 52
  batch_size: 766
  weight_factor: 0.24879
  epochs: 44
settings:
  split: 0.08574
  estimators: 50
model:
  split: 0.48411
