tagging:
  trees: 67
  epochs: 29
  folds: 11
  estimators: 166
  seed: 453219048
concurrent:
  weight_factor: 0.18715
  ngrams: 4
  passes: 1
  features: 2684
  estimators: 130
train:
  estimators: 52
  batch_size: 766
  weight_factor: 0.24879
  epochs: 44
settings:
  split: 0.08026
  estimators: 50
model:
  split: 0.62394
