tagging:
  trees: 78
  epochs: 23
  folds: 10
  estimators: 166
  seed: 527774928
concurrent:
  weight_factor: 0.192
  ngrams: 4
  passes: 2
  features: 2361
  estimators: 127
train:
  estimators: 48
  batch_size: 945
  weight_factor: 0.22383
  epochs: 44
settings:
  split: 0.08028
  estimators: 50
model:
  split: 0.62394
