tagging:
  trees: 91
  epochs: 24
  folds: 11
  estimators: 189
  seed: 417151150
concurrent:
  weight_factor: 0.19009
  ngrams: 3
  passes: 2
  features: 2974
  estimators: 188
train:
  estimators: 64
  batch_size: 655
  weight_factor: 0.19211
  epochs: 30
settings:
  split: 0.11426
  estimators: 51
model:
  split: 0.61034
