tagging:
  trees: 91
  epochs: 24
  folds: 9
  estimators: 138
  seed: 417151150
concurrent:
  weight_factor: 0.16574
  ngrams: 3
  passes: 2
  features: 2974
  estimators: 172
train:
  estimators: 64
  batch_size: 633
  weight_factor: 0.19211
  epochs: 30
settings:
  split: 0.11426
  estimators: 54
model:
  split: 0.50429
