tagging:
  trees: 88
  epochs: 24
  folds: 14
  estimators: 138
  seed: 417151150
concurrent:
  weight_factor: 0.16579
  ngrams: 3
  passes: 1
  features: 2974
  estimators: 172
train:
  estimators: 44
  batch_size: 946
  weight_factor: 0.15841
  epochs: 45
settings:
  split: 0.11426
  estimators: 54
model:
  split: 0.56688
