tagging:
  trees: 79
  epochs: 21
  folds: 10
  estimators: 177
  seed: 417151150
concurrent:
  weight_factor: 0.19009
  ngrams: 4
  passes: 2
  features: 2974
  estimators: 141
train:
  estimators: 64
  batch_size: 800
  weight_factor: 0.19211
  epochs: 44
settings:
  split: 0.10289
  estimators: 51
model:
  split: 0.56222
