tagging:
  trees: 79
  epochs: 23
  folds: 10
  estimators: 166
  seed: 417151150
concurrent:
  weight_factor: 0.192
  ngrams: 4
  passes: 2
  features: 2361
  estimators: 127
train:
  estimators: 47
  batch_size: 800
  weight_factor: 0.22917
  epochs: 44
settings:
  split: 0.11147
  estimators: 59
model:
  split: 0.62394
