tagging:
  trees: 82
  epochs: 25
  folds: 13
  estimators: 223
  seed: 567277192
concurrent:
  weight_factor: 0.19374
  ngrams: 4
  passes: 2
  features: 2428
  estimators: 134
train:
  estimators: 44
  batch_size: 707
  weight_factor: 0.22714
  epochs: 33
settings:
  split: 0.10683
  estimators: 57
model:
  split: 0.3902
