tagging:
  trees: 59
  epochs: 27
  folds: 14
  estimators: 224
  seed: 451228327
concurrent:
  weight_factor: 0.23465
  ngrams: 4
  passes: 1
  features: 3350
  estimators: 130
train:
  estimators: 52
  batch_size: 677
  weight_factor: 0.24879
  epochs: 44
settings:
  split: 0.08574
  estimators: 50
model:
  split: 0.48411
