tagging:
  trees: 65
  epochs: 24
  folds: 14
  estimators: 168
  seed: 417151150
concurrent:
  weight_factor: 0.16754
  ngrams: 4
  passes: 1
  features: 2974
  estimators: 144
train:
  estimators: 64
  batch_size: 982
  weight_factor: 0.15841
  epochs: 41
settings:
  split: 0.0811
  estimators: 43
model:
  split: 0.5613
