tagging:
  trees: 58
  epochs: 25
  folds: 14
  estimators: 223
  seed: 473825141
concurrent:
  weight_factor: 0.16381
  ngrams: 4
  passes: 2
  features: 2960
  estimators: 138
train:
  estimators: 47
  batch_size: 926
  weight_factor: 0.22714
  epochs: 33
settings:
  split: 0.0811
  estimators: 45
model:
  split: 0.3902
