tagging:
  trees: 59
  epochs: 27
  folds: 12
  estimators: 156
  seed: 500277000
concurrent:
  weight_factor: 0.19721
  ngrams: 4
  passes: 1
  features: 3350
  estimators: 160
train:
  estimators: 59
  batch_size: 677
  weight_factor: 0.24879
  epochs: 48
settings:
  split: 0.08574
  estimators: 50
model:
  split: 0.48411
