tagging:
  trees: 78
  epochs: 26
  folds: 11
  estimators: 166
  seed: 453219048
concurrent:
  weight_factor: 0.22749
  ngrams: 4
  passes: 1
  features: 2684
  estimators: 127
train:
  estimators: 64
  batch_size: 766
  weight_factor: 0.24879
  epochs: 44
settings:
  split: 0.08028
  estimators: 50
model:
  split: 0.62394
