prepare:
  min_split: 70
  dense: 317
  passes: 12
  num_est: 257
train:
  min_split: 71
  estimators: 50
  min_features: 4000
  max_features: 1600
  columns: 15
  threads: 2
model:
  random_state: 727168549
  max_depth: 32
  split: 0.1
  ngrams: 2
  threads: 16
  max_features: 1052
  num_est: 112
  folds: 5
  passes: 6
variables:
  sample: 0.75
  num_est: 69
  min_split: 65
  columns: 18
  weight_factor: 0.2
  features: 6058
validation:
  learning_rate: 0.04
  weight_factor: 0.3
  seed: 71137302
  features: 1232
  ngrams: 5
  min_split: 64
