prepare:
  min_split: 68
  dense: 290
  passes: 18
  num_est: 193
train:
  min_split: 78
  estimators: 37
  min_features: 3929
  max_features: 1716
  columns: 14
  threads: 2
model:
  random_state: 714328618
  max_depth: 32
  split: 0.1
  ngrams: 2
  threads: 22
  max_features: 1276
  num_est: 80
  folds: 5
  passes: 6
variables:
  sample: 0.877
  num_est: 69
  min_split: 62
  columns: 14
  weight_factor: 0.17419
  features: 6058
validation:
  learning_rate: 0.04
  weight_factor: 0.27834
  seed: 70817687
  features: 1232
  ngrams: 4
  min_split: 55
