prepare:
  min_split: 52
  dense: 290
  passes: 16
  num_est: 204
train:
  min_split: 78
  estimators: 46
  min_features: 3996
  max_features: 1311
  columns: 16
  threads: 2
model:
  random_state: 472619921
  max_depth: 32
  split: 0.10941
  ngrams: 1
  threads: 18
  max_features: 1478
  num_est: 96
  folds: 5
  passes: 5
variables:
  sample: 0.84145
  num_est: 64
  min_split: 76
  columns: 15
  weight_factor: 0.17419
  features: 4194
validation:
  learning_rate: 0.04542
  weight_factor: 0.23806
  seed: 70817687
  features: 1179
  ngrams: 4
  min_split: 55
