prepare:
  min_split: 50
  dense: 354
  passes: 12
  num_est: 285
train:
  min_split: 64
  estimators: 50
  min_features: 4000
  max_features: 1600
  columns: 15
  threads: 2
model:
  random_state: 727168549
  max_depth: 31
  split: 0.1
  ngrams: 2
  threads: 17
  max_features: 1052
  num_est: 112
  folds: 5
  passes: 6
variables:
  sample: 0.75
  num_est: 69
  min_split: 83
  columns: 15
  weight_factor: 0.2
  features: 6058
validation:
  learning_rate: 0.04
  weight_factor: 0.3
  seed: 71182000
  features: 1190
  ngrams: 6
  min_split: 64
