prepare:
  min_split: 52
  dense: 290
  passes: 13
  num_est: 204
train:
  min_split: 78
  estimators: 32
  min_features: 4211
  max_features: 1311
  columns: 16
  threads: 2
model:
  random_state: 714328618
  max_depth: 32
  split: 0.1
  ngrams: 2
  threads: 18
  max_features: 1478
  num_est: 80
  folds: 5
  passes: 5
variables:
  sample: 0.877
  num_est: 69
  min_split: 62
  columns: 22
  weight_factor: 0.17419
  features: 6090
validation:
  learning_rate: 0.04542
  weight_factor: 0.22699
  seed: 70817687
  features: 1226
  ngrams: 4
  min_split: 55
