prepare:
  min_split: 49
  dense: 253
  passes: 12
  num_est: 284
train:
  min_split: 57
  estimators: 49
  min_features: 3103
  max_features: 1252
  columns: 13
  threads: 1
model:
  random_state: 493655995
  max_depth: 29
  split: 0.08844
  ngrams: 2
  threads: 24
  max_features: 1204
  num_est: 96
  folds: 5
  passes: 6
variables:
  sample: 0.67622
  num_est: 58
  min_split: 76
  columns: 15
  weight_factor: 0.22878
  features: 4194
validation:
  learning_rate: 0.04415
  weight_factor: 0.28561
  seed: 61322272
  features: 1179
  ngrams: 4
  min_split: 48
