prepare:
  min_split: 67
  dense: 324
  passes: 17
  num_est: 258
train:
  min_split: 78
  estimators: 32
  min_features: 3103
  max_features: 1252
  columns: 16
  threads: 2
model:
  random_state: 472619921
  max_depth: 32
  split: 0.10941
  ngrams: 2
  threads: 24
  max_features: 1155
  num_est: 96
  folds: 5
  passes: 6
variables:
  sample: 0.62285
  num_est: 85
  min_split: 76
  columns: 15
  weight_factor: 0.17419
  features: 4194
validation:
  learning_rate: 0.04415
  weight_factor: 0.23806
  seed: 70817687
  features: 1179
  ngrams: 4
  min_split: 71
