prepare:
  min_split: 68
  dense: 339
  passes: 18
  num_est: 193
train:
  min_split: 71
  estimators: 50
  min_features: 4000
  max_features: 1716
  columns: 15
  threads: 2
model:
  random_state: 727168549
  max_depth: 32
  split: 0.1
  ngrams: 2
  threads: 22
  max_features: 1425
  num_est: 79
  folds: 5
  passes: 6
variables:
  sample: 0.59391
  num_est: 69
  min_split: 62
  columns: 14
  weight_factor: 0.2087
  features: 6058
validation:
  learning_rate: 0.04
  weight_factor: 0.36561
  seed: 84385554
  features: 1232
  ngrams: 6
  min_split: 59
