stages:
  split:
    cmd: python split.py phrases.csv phrases-train.csv phrases-test.csv
    deps:
    - phrases.csv
    - split.py
    outs:
    - phrases-test.csv
    - phrases-train.csv
  featurize:
    cmd: python featurize.py phrases-train.csv phrases-train-feats.csv
    deps:
    - featurize.py
    - phrases-train.csv
    params:
    - featurize.estimators
    - featurize.layers
    - featurize.ngrams
    - featurize.tags
    - featurize.threads
    - featurize.trees
    outs:
    - phrases-train-feats.csv
  train:
    cmd: python train.py phrases-train-feats.csv model.json
    deps:
    - phrases-train-feats.csv
    - train.py
    params:
    - concurrent.epochs
    - concurrent.features
    - concurrent.layers
    - concurrent.trees
    - tagging.dense
    - tagging.epochs
    - tagging.max_depth
    - tagging.ngrams
    - tagging.sample
    - tagging.weight_factor
    - train.batch_size
    - train.features
    - train.folds
    - train.layers
    - train.num_est
    - train.seed
    - train.tags
    - train.trees
    - variables.max_depth
    - variables.random_state
    - variables.split
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json phrases-test.csv
    deps:
    - evaluate.py
    - model.json
    - phrases-test.csv
    metrics:
    - metrics.json:
        cache: false
