variables:
  max_depth: 4
  random_state: 47353310
  split: 0.5
train:
  features: 2234
  folds: 3
  layers: 2
  num_est: 203
  seed: 205696000
  tags: 66
  batch_size: 576
  trees: 26
concurrent:
  trees: 52
  features: 2520
  epochs: 48
  layers: 6
featurize:
  threads: 30
  estimators: 140
  trees: 51
  tags: 54
  layers: 4
  ngrams: 4
tagging:
  dense: 500
  epochs: 16
  sample: 0.25
  weight_factor: 0.25645
  max_depth: 4
  ngrams: 5
