variables:
  max_depth: 4
  random_state: 42962714
  split: 0.39011
train:
  features: 1841
  folds: 2
  layers: 2
  num_est: 165
  seed: 234387773
  tags: 59
  batch_size: 588
  trees: 18
concurrent:
  trees: 57
  features: 3000
  epochs: 44
  layers: 4
featurize:
  threads: 21
  estimators: 144
  trees: 36
  tags: 59
  layers: 3
  ngrams: 6
tagging:
  dense: 437
  epochs: 12
  sample: 0.19532
  weight_factor: 0.3237
  max_depth: 3
  ngrams: 6
