variables:
  max_depth: 4
  random_state: 37271993
  split: 0.40194
train:
  features: 2583
  folds: 2
  layers: 2
  num_est: 184
  seed: 242510001
  tags: 68
  batch_size: 568
  trees: 25
concurrent:
  trees: 50
  features: 2176
  epochs: 66
  layers: 4
featurize:
  threads: 25
  estimators: 131
  trees: 37
  tags: 67
  layers: 3
  ngrams: 7
tagging:
  dense: 424
  epochs: 12
  sample: 0.27073
  weight_factor: 0.33461
  max_depth: 3
  ngrams: 5
