variables:
  max_depth: 4
  random_state: 42502577
  split: 0.56917
train:
  features: 1890
  folds: 2
  layers: 1
  num_est: 229
  seed: 229488276
  tags: 47
  batch_size: 653
  trees: 18
concurrent:
  trees: 52
  features: 1972
  epochs: 64
  layers: 4
featurize:
  threads: 32
  estimators: 98
  trees: 55
  tags: 55
  layers: 4
  ngrams: 5
tagging:
  dense: 609
  epochs: 13
  sample: 0.18998
  weight_factor: 0.3237
  max_depth: 4
  ngrams: 5
