variables:
  max_depth: 3
  random_state: 49638038
  split: 0.42712
train:
  features: 1841
  folds: 2
  layers: 1
  num_est: 165
  seed: 240221571
  tags: 68
  batch_size: 636
  trees: 25
concurrent:
  trees: 62
  features: 2252
  epochs: 45
  layers: 4
featurize:
  threads: 25
  estimators: 92
  trees: 50
  tags: 59
  layers: 3
  ngrams: 4
tagging:
  dense: 384
  epochs: 17
  sample: 0.19246
  weight_factor: 0.31451
  max_depth: 4
  ngrams: 6
