variables:
  max_depth: 4
  random_state: 54029245
  split: 0.59998
train:
  features: 1890
  folds: 2
  layers: 2
  num_est: 156
  seed: 229488276
  tags: 47
  batch_size: 588
  trees: 18
concurrent:
  trees: 57
  features: 1972
  epochs: 64
  layers: 4
featurize:
  threads: 24
  estimators: 110
  trees: 38
  tags: 65
  layers: 4
  ngrams: 6
tagging:
  dense: 589
  epochs: 11
  sample: 0.18998
  weight_factor: 0.3237
  max_depth: 4
  ngrams: 5
