variables:
  max_depth: 3
  random_state: 45946745
  split: 0.61839
train:
  features: 2583
  folds: 2
  layers: 2
  num_est: 185
  seed: 161542173
  tags: 63
  batch_size: 454
  trees: 25
concurrent:
  trees: 50
  features: 2905
  epochs: 66
  layers: 5
featurize:
  threads: 21
  estimators: 102
  trees: 44
  tags: 58
  layers: 3
  ngrams: 7
tagging:
  dense: 381
  epochs: 13
  sample: 0.2432
  weight_factor: 0.33461
  max_depth: 3
  ngrams: 5
