variables:
  max_depth: 3
  random_state: 37406032
  split: 0.39011
train:
  features: 1841
  folds: 2
  layers: 2
  num_est: 165
  seed: 240221571
  tags: 54
  batch_size: 636
  trees: 25
concurrent:
  trees: 61
  features: 2261
  epochs: 45
  layers: 4
featurize:
  threads: 25
  estimators: 92
  trees: 50
  tags: 59
  layers: 3
  ngrams: 4
tagging:
  dense: 604
  epochs: 13
  sample: 0.22789
  weight_factor: 0.3237
  max_depth: 4
  ngrams: 6
