variables:
  max_depth: 3
  random_state: 41044610
  split: 0.4638
train:
  features: 2583
  folds: 2
  layers: 2
  num_est: 185
  seed: 161542173
  tags: 58
  batch_size: 568
  trees: 25
concurrent:
  trees: 50
  features: 2027
  epochs: 66
  layers: 5
featurize:
  threads: 21
  estimators: 102
  trees: 44
  tags: 58
  layers: 3
  ngrams: 7
tagging:
  dense: 424
  epochs: 13
  sample: 0.2432
  weight_factor: 0.33461
  max_depth: 3
  ngrams: 5
