variables:
  max_depth: 4
  random_state: 42502577
  split: 0.56917
train:
  features: 1890
  folds: 2
  layers: 1
  num_est: 229
  seed: 211220253
  tags: 52
  batch_size: 653
  trees: 22
concurrent:
  trees: 52
  features: 1972
  epochs: 64
  layers: 6
featurize:
  threads: 25
  estimators: 98
  trees: 34
  tags: 55
  layers: 4
  ngrams: 5
tagging:
  dense: 534
  epochs: 13
  sample: 0.28409
  weight_factor: 0.29708
  max_depth: 4
  ngrams: 5
