variables:
  max_depth: 4
  random_state: 47353310
  split: 0.6154
train:
  features: 1793
  folds: 2
  layers: 1
  num_est: 171
  seed: 239566251
  tags: 67
  batch_size: 576
  trees: 26
concurrent:
  trees: 53
  features: 2520
  epochs: 66
  layers: 4
featurize:
  threads: 33
  estimators: 100
  trees: 33
  tags: 68
  layers: 4
  ngrams: 6
tagging:
  dense: 604
  epochs: 11
  sample: 0.21868
  weight_factor: 0.32474
  max_depth: 4
  ngrams: 4
