variables:
  max_depth: 3
  random_state: 35679747
  split: 0.443
train:
  features: 2268
  folds: 2
  layers: 2
  num_est: 171
  seed: 161542173
  tags: 60
  batch_size: 610
  trees: 26
concurrent:
  trees: 50
  features: 2905
  epochs: 60
  layers: 5
featurize:
  threads: 23
  estimators: 135
  trees: 34
  tags: 61
  layers: 3
  ngrams: 5
tagging:
  dense: 569
  epochs: 16
  sample: 0.2432
  weight_factor: 0.30095
  max_depth: 4
  ngrams: 5
