variables:
  max_depth: 4
  random_state: 35097535
  split: 0.51687
train:
  features: 1793
  folds: 2
  layers: 1
  num_est: 171
  seed: 222712654
  tags: 67
  batch_size: 576
  trees: 22
concurrent:
  trees: 53
  features: 2520
  epochs: 61
  layers: 4
featurize:
  threads: 33
  estimators: 91
  trees: 33
  tags: 68
  layers: 4
  ngrams: 6
tagging:
  dense: 504
  epochs: 17
  sample: 0.20743
  weight_factor: 0.28516
  max_depth: 4
  ngrams: 4
