variables:
  max_depth: 4
  random_state: 36954175
  split: 0.42712
train:
  features: 1800
  folds: 3
  layers: 2
  num_est: 192
  seed: 240221571
  tags: 68
  batch_size: 568
  trees: 25
concurrent:
  trees: 62
  features: 3026
  epochs: 45
  layers: 4
featurize:
  threads: 25
  estimators: 94
  trees: 51
  tags: 59
  layers: 4
  ngrams: 4
tagging:
  dense: 424
  epochs: 17
  sample: 0.19246
  weight_factor: 0.28432
  max_depth: 4
  ngrams: 6
