variables:
  max_depth: 4
  random_state: 53766682
  split: 0.39011
train:
  features: 1841
  folds: 2
  layers: 2
  num_est: 165
  seed: 240221571
  tags: 54
  batch_size: 636
  trees: 18
concurrent:
  trees: 57
  features: 3000
  epochs: 44
  layers: 4
featurize:
  threads: 31
  estimators: 145
  trees: 44
  tags: 48
  layers: 4
  ngrams: 7
tagging:
  dense: 437
  epochs: 13
  sample: 0.21034
  weight_factor: 0.3237
  max_depth: 3
  ngrams: 6
