variables:
  max_depth: 3
  random_state: 35679747
  split: 0.51687
train:
  features: 2268
  folds: 2
  layers: 1
  num_est: 171
  seed: 161542173
  tags: 60
  batch_size: 610
  trees: 26
concurrent:
  trees: 50
  features: 2905
  epochs: 59
  layers: 5
featurize:
  threads: 21
  estimators: 90
  trees: 34
  tags: 48
  layers: 4
  ngrams: 7
tagging:
  dense: 504
  epochs: 16
  sample: 0.2432
  weight_factor: 0.30095
  max_depth: 3
  ngrams: 5
