variables:
  max_depth: 4
  random_state: 54029245
  split: 0.56917
train:
  features: 1890
  folds: 2
  layers: 2
  num_est: 229
  seed: 229488276
  tags: 69
  batch_size: 588
  trees: 18
concurrent:
  trees: 57
  features: 1972
  epochs: 64
  layers: 4
featurize:
  threads: 30
  estimators: 98
  trees: 36
  tags: 54
  layers: 4
  ngrams: 6
tagging:
  dense: 604
  epochs: 11
  sample: 0.18998
  weight_factor: 0.3237
  max_depth: 4
  ngrams: 5
