variables:
  max_depth: 4
  random_state: 35679747
  split: 0.51687
train:
  features: 2276
  folds: 3
  layers: 1
  num_est: 171
  seed: 161542173
  tags: 60
  batch_size: 576
  trees: 26
concurrent:
  trees: 53
  features: 2520
  epochs: 59
  layers: 5
featurize:
  threads: 31
  estimators: 90
  trees: 34
  tags: 52
  layers: 3
  ngrams: 6
tagging:
  dense: 504
  epochs: 11
  sample: 0.2432
  weight_factor: 0.26141
  max_depth: 4
  ngrams: 6
