variables:
  max_depth: 3
  random_state: 42502577
  split: 0.56917
train:
  features: 1890
  folds: 2
  layers: 1
  num_est: 168
  seed: 211220253
  tags: 47
  batch_size: 653
  trees: 22
concurrent:
  trees: 52
  features: 2220
  epochs: 63
  layers: 5
featurize:
  threads: 33
  estimators: 127
  trees: 45
  tags: 46
  layers: 3
  ngrams: 6
tagging:
  dense: 534
  epochs: 11
  sample: 0.28409
  weight_factor: 0.29708
  max_depth: 4
  ngrams: 4
