variables:
  max_depth: 4
  random_state: 47353310
  split: 0.5
train:
  features: 1793
  folds: 2
  layers: 1
  num_est: 203
  seed: 205696000
  tags: 67
  batch_size: 576
  trees: 26
concurrent:
  trees: 53
  features: 2520
  epochs: 48
  layers: 5
featurize:
  threads: 31
  estimators: 100
  trees: 48
  tags: 44
  layers: 3
  ngrams: 6
tagging:
  dense: 604
  epochs: 16
  sample: 0.25
  weight_factor: 0.25645
  max_depth: 4
  ngrams: 5
