variables:
  max_depth: 4
  random_state: 54029245
  split: 0.39011
train:
  features: 1890
  folds: 2
  layers: 2
  num_est: 156
  seed: 229488276
  tags: 47
  batch_size: 588
  trees: 26
concurrent:
  trees: 57
  features: 1972
  epochs: 64
  layers: 4
featurize:
  threads: 27
  estimators: 93
  trees: 37
  tags: 58
  layers: 4
  ngrams: 5
tagging:
  dense: 589
  epochs: 11
  sample: 0.28168
  weight_factor: 0.3237
  max_depth: 3
  ngrams: 5
