variables:
  max_depth: 4
  random_state: 35097535
  split: 0.51687
train:
  features: 1793
  folds: 2
  layers: 1
  num_est: 171
  seed: 222712654
  tags: 60
  batch_size: 576
  trees: 26
concurrent:
  trees: 53
  features: 2520
  epochs: 59
  layers: 4
featurize:
  threads: 22
  estimators: 91
  trees: 34
  tags: 61
  layers: 4
  ngrams: 6
tagging:
  dense: 504
  epochs: 11
  sample: 0.2432
  weight_factor: 0.26141
  max_depth: 4
  ngrams: 6
