variables:
  max_depth: 3
  random_state: 37621115
  split: 0.39011
train:
  features: 1841
  folds: 2
  layers: 2
  num_est: 165
  seed: 240221571
  tags: 54
  batch_size: 636
  trees: 18
concurrent:
  trees: 57
  features: 3000
  epochs: 44
  layers: 4
featurize:
  threads: 25
  estimators: 122
  trees: 48
  tags: 59
  layers: 3
  ngrams: 4
tagging:
  dense: 437
  epochs: 13
  sample: 0.21034
  weight_factor: 0.3237
  max_depth: 4
  ngrams: 6
