concurrent:
  ngrams: 4
  random_state: 75378570
  split: 0.20094
  columns: 44
  features: 1503
model:
  tags: 100
  estimators: 21
  columns: 20
  passes: 131
  min_split: 24
  dense: 233
tagging:
  learning_rate: 0.08631
  features: 3408
  min_features: 3961
settings:
  batch_size: 585
  num_est: 87
  min_features: 1195
  passes: 60
validation:
  split: 0.39586
  min_split: 48
  layers: 2
  num_est: 144
