concurrent:
  ngrams: 5
  random_state: 98659984
  split: 0.19536
  columns: 61
  features: 1503
model:
  tags: 74
  estimators: 17
  columns: 29
  passes: 118
  min_split: 24
  dense: 241
tagging:
  learning_rate: 0.08355
  features: 3770
  min_features: 3808
settings:
  batch_size: 527
  num_est: 64
  min_features: 1456
  passes: 68
validation:
  split: 0.34309
  min_split: 38
  layers: 2
  num_est: 187
