concurrent:
  ngrams: 6
  random_state: 83000000
  split: 0.2
  columns: 44
  features: 1071
model:
  tags: 90
  estimators: 21
  columns: 27
  passes: 120
  min_split: 32
  dense: 200
tagging:
  learning_rate: 0.07
  features: 3500
  min_features: 4000
settings:
  batch_size: 672
  num_est: 67
  min_features: 1500
  passes: 94
validation:
  split: 0.4
  min_split: 48
  layers: 2
  num_est: 150
