concurrent:
  ngrams: 4
  random_state: 65020193
  split: 0.2271
  columns: 44
  features: 1150
model:
  tags: 111
  estimators: 22
  columns: 21
  passes: 131
  min_split: 38
  dense: 245
tagging:
  learning_rate: 0.0573
  features: 3408
  min_features: 4146
settings:
  batch_size: 585
  num_est: 71
  min_features: 1438
  passes: 60
validation:
  split: 0.39586
  min_split: 46
  layers: 2
  num_est: 145
