concurrent:
  ngrams: 5
  random_state: 65020193
  split: 0.2271
  columns: 44
  features: 1382
model:
  tags: 111
  estimators: 21
  columns: 24
  passes: 97
  min_split: 38
  dense: 245
tagging:
  learning_rate: 0.0573
  features: 3408
  min_features: 3122
settings:
  batch_size: 585
  num_est: 85
  min_features: 1714
  passes: 60
validation:
  split: 0.47799
  min_split: 46
  layers: 1
  num_est: 145
