concurrent:
  ngrams: 7
  random_state: 75378570
  split: 0.20124
  columns: 44
  features: 1503
model:
  tags: 100
  estimators: 17
  columns: 27
  passes: 125
  min_split: 32
  dense: 184
tagging:
  learning_rate: 0.05705
  features: 4280
  min_features: 4013
settings:
  batch_size: 694
  num_est: 84
  min_features: 1141
  passes: 80
validation:
  split: 0.39586
  min_split: 59
  layers: 2
  num_est: 144
