concurrent:
  ngrams: 5
  random_state: 76798585
  split: 0.19536
  columns: 61
  features: 1503
model:
  tags: 106
  estimators: 17
  columns: 29
  passes: 118
  min_split: 27
  dense: 245
tagging:
  learning_rate: 0.08713
  features: 3792
  min_features: 3808
settings:
  batch_size: 527
  num_est: 64
  min_features: 1456
  passes: 68
validation:
  split: 0.34309
  min_split: 38
  layers: 2
  num_est: 187
