concurrent:
  ngrams: 5
  random_state: 75378570
  split: 0.20094
  columns: 44
  features: 1503
model:
  tags: 100
  estimators: 25
  columns: 27
  passes: 131
  min_split: 32
  dense: 166
tagging:
  learning_rate: 0.05605
  features: 3935
  min_features: 4013
settings:
  batch_size: 585
  num_est: 71
  min_features: 1195
  passes: 82
validation:
  split: 0.39586
  min_split: 59
  layers: 2
  num_est: 144
