concurrent:
  ngrams: 5
  random_state: 98659984
  split: 0.19536
  columns: 61
  features: 1503
model:
  tags: 100
  estimators: 17
  columns: 29
  passes: 118
  min_split: 32
  dense: 175
tagging:
  learning_rate: 0.08355
  features: 3770
  min_features: 3808
settings:
  batch_size: 527
  num_est: 69
  min_features: 1456
  passes: 80
validation:
  split: 0.47024
  min_split: 38
  layers: 2
  num_est: 154
