concurrent:
  ngrams: 5
  random_state: 93397504
  split: 0.2
  columns: 61
  features: 1071
model:
  tags: 71
  estimators: 17
  columns: 27
  passes: 93
  min_split: 28
  dense: 172
tagging:
  learning_rate: 0.07738
  features: 4098
  min_features: 4843
settings:
  batch_size: 759
  num_est: 67
  min_features: 1654
  passes: 98
validation:
  split: 0.49628
  min_split: 36
  layers: 1
  num_est: 119
