concurrent:
  ngrams: 7
  random_state: 65088950
  split: 0.2
  columns: 39
  features: 1071
model:
  tags: 90
  estimators: 23
  columns: 24
  passes: 120
  min_split: 32
  dense: 200
tagging:
  learning_rate: 0.07
  features: 3500
  min_features: 4843
settings:
  batch_size: 759
  num_est: 77
  min_features: 1825
  passes: 94
validation:
  split: 0.4
  min_split: 48
  layers: 2
  num_est: 150
