concurrent:
  ngrams: 5
  random_state: 67507996
  split: 0.2
  columns: 61
  features: 1071
model:
  tags: 90
  estimators: 23
  columns: 20
  passes: 101
  min_split: 28
  dense: 230
tagging:
  learning_rate: 0.07738
  features: 4098
  min_features: 4843
settings:
  batch_size: 759
  num_est: 88
  min_features: 1654
  passes: 94
validation:
  split: 0.49628
  min_split: 36
  layers: 1
  num_est: 128
