concurrent:
  ngrams: 5
  random_state: 89873151
  split: 0.19536
  columns: 61
  features: 1270
model:
  tags: 71
  estimators: 17
  columns: 27
  passes: 96
  min_split: 28
  dense: 248
tagging:
  learning_rate: 0.07496
  features: 3792
  min_features: 3070
settings:
  batch_size: 527
  num_est: 74
  min_features: 1456
  passes: 65
validation:
  split: 0.36286
  min_split: 58
  layers: 2
  num_est: 113
